# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
  - master
  - feature/*

pool:
  name: 'Default'

variables:
  imageName: estudomensageria

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build --configuration Release
  displayName: 'Build application'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish application'

# Build Docker image
- script: |
    docker build -t $(imageName):$(Build.BuildId) .
  displayName: 'Build Docker image'