# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
  - master
  - feature/*

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  artifactName: 'drop'
  iisPath: './Adapters/Api/ProducerProject/ProducerProject.csproj'

stages:
# -------------------- BUILD --------------------
- stage: Build
  displayName: Build & Publish
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'          # ajuste para sua versão

    - script: |
        dotnet restore $(iisPath)
        dotnet build $(iisPath) -c $(buildConfiguration) --no-restore
        dotnet publish $(iisPath) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish --no-build
      displayName: 'Restore/Build/Publish'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop/drop.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
        ArtifactName: 'drop'
        publishLocation: 'Container'
