version: '3.8'
services:
  apiconsumer:
    build: 
        context: .
        dockerfile: /ConsumerProject/Dockerfile
    depends_on:
        - sqlserver
        - rabbitmq
    ports:
        - "5623:80"
    environment:
      - "ConnectionStrings__DbConnection=Server=sqlserver;Initial Catalog=rabbitmq_database;User Id=sa;Password=@62745623Tk; TrustServerCertificate=True;"
      - "AccessKey=anderson"
      - "SecretKey=62745623"
      - "MassTransient:enable=true"
      - "RabbitMq:url=rabbitmq"
      - "ASPNETCORE_ENVIRONMENT=staging"
    networks:
        - rabbitmq_net

  apiproducer:
    build:
        context: .
        dockerfile: /EstudoMensageria/Dockerfile
    depends_on:
        - rabbitmq
    ports:
        - "5621:80"
    environment:
        - "AccessKey=anderson"
        - "SecretKey=62745623"
        - "MassTransient:enable=true"
        - "RabbitMq:url=rabbitmq"
        - "ASPNETCORE_ENVIRONMENT=staging"
    networks:
        - rabbitmq_net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '@62745623Tk'
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - rabbitmq_net

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "anderson"
      RABBITMQ_DEFAULT_PASS: "62745623"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - rabbitmq_net

volumes:
  sql_data:
  rabbitmq_data:

networks:
  rabbitmq_net:
